name: flutter_chat_ui
version: 2.0.0-dev.8
description: >
  Community-driven, animated chat UI for Flutter with top-tier performance and
  customization for chat apps and generative AI agents. #firebase #gemini #chatgpt
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  cross_cache: ^0.0.9
  diffutil_dart: ^4.0.1
  flutter:
    sdk: flutter
  flutter_chat_core: 
    git:
      url: https://github.com/johnstef99/flutter_chat_ui.git
      ref: main
      path: packages/flutter_chat_core
  provider: ^6.1.2
  scrollview_observer: ^1.25.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
