name: flyer_chat_text_message
version: 0.0.9
description: >
  Text message package for Flutter chat apps, complementing flutter_chat_ui. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: 
    git:
      url: https://github.com/johnstef99/flutter_chat_ui.git
      ref: main
      path: packages/flutter_chat_core
  gpt_markdown: ^1.0.12
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
