name: flyer_chat_image_message
version: 0.0.9
description: >
  Image message package for Flutter chat apps, complementing flutter_chat_ui.
  Supports caching, ThumbHash and BlurHash. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  blurhash_dart: ^1.2.1
  cross_cache: ^0.0.9
  flutter:
    sdk: flutter
  flutter_chat_core: 
    git:
      url: https://github.com/johnstef99/flutter_chat_ui.git
      ref: main
      path: packages/flutter_chat_core
  image: ^4.5.2
  provider: ^6.1.2
  thumbhash: ^0.1.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
